### ISSUE TITLE
how to import `sys_dict` and `user_dict`

### ISSUE THREAD

**Issue by kouui** [nakagami/janomecabdic#1]
Hi. Excellent work which saves a lot of janome dictionary compilation time.
From your example, it seems that one is able to replace `janome`'s default `sys_dict` by your `MeCabDictionary()`, which imports the system dictionary from mecab.
Is there any way to import the user dictionary from mecab? or how to use `janomecabdic` provided a mecab `*.dic` file.
My aim is to import the system dictionary and user dictionary together from mecab to janome.

**Comment by nakagami** [comment]
janomecabdic can only replace the system dictionary.
I think there is a way to specify a user dictionary in janome, please use it.
